// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DarkToggle: typeof import('./../components/DarkToggle.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconCustomFace: typeof import('~icons/custom/face')['default']
    IconCustomIconFace: typeof import('~icons/custom/icon-face')['default']
    IconCustomMoon: typeof import('~icons/custom/moon')['default']
    IconCustomSun: typeof import('~icons/custom/sun')['default']
  }
}

export { }
